openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        image_name:
          title: 镜像名
          type: string
          description: Name for the zabbix server image
          default: zabbix-by-terraform
          x-walrus-ui:
            group: Basic
            order: 2
        image_url:
          title: 镜像 Url
          type: string
          description: URL to download the image from
          default: http://minio.zstack.io:9001/packer/zabbix-by-packer-image-compressed.qcow2
          x-walrus-ui:
            group: Basic
            order: 3
        backup_storage_name:
          title: 镜像服务器
          type: string
          description: Name of the backup storage to use
          default: bs
          x-walrus-ui:
            group: Basic
            order: 4
        instance_name:
          title: 云主机名称
          type: string
          description: Name for the zabbix server instance
          default: zabbix
          x-walrus-ui:
            group: Basic
            order: 5
        l3_network_name:
          title: 三层网络名称
          type: string
          description: Name of the L3 network to use
          default: test
          x-walrus-ui:
            group: Basic
            order: 6
        instance_offering_name:
          title: 计算规格名称
          type: string
          description: Name of the instance offering to use
          default: min
          x-walrus-ui:
            group: Basic
            order: 7
        zbx_user:
          title: Zabbix 用户名
          type: string
          description: username for Zabbix Admin
          default: Admin
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        zbxpassword:
          title: Zabbix 密码
          type: string
          description: password for Zabbix Admin
          default: zabbix
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        port:
          title: Port
          type: number
          description: The port on which the zabbix will listen
          default: 80
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 10
        expunge:
          title: 是否彻底删除
          type: boolean
          default: true
          x-walrus-ui:
            group: Basic
            order: 11
      x-walrus-ui:
        groupOrder:
        - Basic
